Add dependencies for tools-pocolog_pybind
esa-prl/rover-package_set pull request #10
Opened 2021-02-02 20:56 UTC by mstoelzle

- Add pybind11 as external/pybind
- Pybind requires ninja-build
- Activate python3 installations deactivated in rock-core package set

@levingerdes I will remove the wrong commit authors with a squash merge at the end

2021-02-03 11:04 UTC, mstoelzle commented
@levingerdes I tested it on a fresh docker image and it seems to be working

2021-02-09 10:11 UTC, levingerdes requested changes
I'd just request one tiny change before merging. See my comment in `source.yml`.

2021-02-09 10:11 UTC, levingerdes commented on source.yml
> +    github: pybind/pybind11
Please use the same format here as we do for all the other packages. I know it's two extra lines, but you can then just click on/copy the URL if needed and you specify the branch explicitly.

2021-02-09 10:33 UTC, mstoelzle commented on source.yml
> +    github: pybind/pybind11
Yes, I've changed that. Thanks a lot

2021-02-09 10:38 UTC, levingerdes approved these changes

2021-02-09 10:40 UTC, merged